sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNG3NSXzKNEQXrtvBxU
    access-key-secret: z8PxXLHZlGtlraJOcdvCQcGLGBEmZI
    bucket-name: cool-take-out

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx8f18c72c11fcb12e
    secret: 8cd71fe534f8f1dc547aebfb17606d0a
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
  shop:
    address: 福建省厦门市集美区理工路600号
  baidu:
    ak: XXXXX