sky:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNG3NSXzKNEQXrtvBxU
    access-key-secret: z8PxXLHZlGtlraJOcdvCQcGLGBEmZI
    bucket-name: cool-take-out

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root